// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMessage(arg1) {
  return window['go']['app']['App']['AbortMessage'](arg1);
}

export function CancelSubAgent(arg1) {
  return window['go']['app']['App']['CancelSubAgent'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['app']['App']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function GetAPIKeyStatus() {
  return window['go']['app']['App']['GetAPIKeyStatus']();
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetModelInfo() {
  return window['go']['app']['App']['GetModelInfo']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSubAgents() {
  return window['go']['app']['App']['GetSubAgents']();
}

export function GetWorkspaceDir() {
  return window['go']['app']['App']['GetWorkspaceDir']();
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListTools() {
  return window['go']['app']['App']['ListTools']();
}

export function OpenDirectoryDialog() {
  return window['go']['app']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['app']['App']['SetAPIKey'](arg1);
}

export function SetThinking(arg1) {
  return window['go']['app']['App']['SetThinking'](arg1);
}

export function SpawnSubAgent(arg1) {
  return window['go']['app']['App']['SpawnSubAgent'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
