// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMessage(arg1) {
  return window['go']['app']['App']['AbortMessage'](arg1);
}

export function ApproveToolCall(arg1) {
  return window['go']['app']['App']['ApproveToolCall'](arg1);
}

export function BranchSession(arg1) {
  return window['go']['app']['App']['BranchSession'](arg1);
}

export function CancelSubAgent(arg1) {
  return window['go']['app']['App']['CancelSubAgent'](arg1);
}

export function ContinueLastResponse(arg1) {
  return window['go']['app']['App']['ContinueLastResponse'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['app']['App']['CreateSession'](arg1);
}

export function GetContextSummary(arg1) {
  return window['go']['app']['App']['GetContextSummary'](arg1);
}

export function UpdateContextSummary(arg1) {
  return window['go']['app']['App']['UpdateContextSummary'](arg1);
}

export function ArchiveSession(arg1) {
  return window['go']['app']['App']['ArchiveSession'](arg1);
}

export function DeleteMessage(arg1) {
  return window['go']['app']['App']['DeleteMessage'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function ExportSettings() {
  return window['go']['app']['App']['ExportSettings']();
}

export function GetAPIKeyStatus() {
  return window['go']['app']['App']['GetAPIKeyStatus']();
}

export function GetDiagnostics() {
  return window['go']['app']['App']['GetDiagnostics']();
}

export function GetHistory(arg1) {
  return window['go']['app']['App']['GetHistory'](arg1);
}

export function GetModelInfo() {
  return window['go']['app']['App']['GetModelInfo']();
}

export function GetOCRAPIKeyStatus() {
  return window['go']['app']['App']['GetOCRAPIKeyStatus']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSubAgents() {
  return window['go']['app']['App']['GetSubAgents']();
}

export function GetWorkspaceDir() {
  return window['go']['app']['App']['GetWorkspaceDir']();
}

export function HideMainWindow() {
  return window['go']['app']['App']['HideMainWindow']();
}

export function ImportSettings() {
  return window['go']['app']['App']['ImportSettings']();
}

export function ImportCharacterCard() {
  return window['go']['app']['App']['ImportCharacterCard']();
}

export function ListDirectory(arg1) {
  return window['go']['app']['App']['ListDirectory'](arg1);
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListTools() {
  return window['go']['app']['App']['ListTools']();
}

export function OpenDirectoryDialog() {
  return window['go']['app']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function ListOCRPresets() {
  return window['go']['app']['App']['ListOCRPresets']();
}

export function OCRImage(arg1) {
  return window['go']['app']['App']['OCRImage'](arg1);
}

export function OCRImageFile(arg1) {
  return window['go']['app']['App']['OCRImageFile'](arg1);
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function ReadFileSnippet(arg1, arg2) {
  return window['go']['app']['App']['ReadFileSnippet'](arg1, arg2);
}

export function RegenerateMessage(arg1) {
  return window['go']['app']['App']['RegenerateMessage'](arg1);
}

export function RejectToolCall(arg1) {
  return window['go']['app']['App']['RejectToolCall'](arg1);
}

export function RestoreMainWindow() {
  return window['go']['app']['App']['RestoreMainWindow']();
}

export function RollbackToolChange(arg1) {
  return window['go']['app']['App']['RollbackToolChange'](arg1);
}

export function SearchWorkspaceFiles(arg1, arg2) {
  return window['go']['app']['App']['SearchWorkspaceFiles'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['app']['App']['SetAPIKey'](arg1);
}

export function SetOCRAPIKey(arg1) {
  return window['go']['app']['App']['SetOCRAPIKey'](arg1);
}

export function SetThinking(arg1) {
  return window['go']['app']['App']['SetThinking'](arg1);
}

export function SpawnSubAgent(arg1) {
  return window['go']['app']['App']['SpawnSubAgent'](arg1);
}

export function TestAPIKey(arg1) {
  return window['go']['app']['App']['TestAPIKey'](arg1);
}

export function UpdateMessage(arg1) {
  return window['go']['app']['App']['UpdateMessage'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
